separate docker image, base and core(python only).

diff --git a/docker/base/dist b/docker/base/dist
--- a/docker/base/dist
+++ b/docker/base/dist
@@ -4,8 +4,18 @@ account="why2pac"
 ver="0.1"
 
 for pyver in py27 py34 py35 pypy27; do
-  sudo docker build --tag $account/dp4p:base-$pyver-$ver --build-arg pyver=$pyver .
-  sudo docker build --tag $account/dp4p:base-$pyver --build-arg pyver=$pyver .
+  sudo docker rmi $account/dp4p:base-$pyver-$ver
+  sudo docker rmi $account/dp4p:base-$pyver
+
+  bash build_docker $pyver dp4p/base-$pyver-$ver
+  bash build_docker $pyver $account/dp4p:base-$pyver-$ver
+  bash build_docker $pyver $account/dp4p:base-$pyver
+
+  if [ "$(sudo docker images | grep $account/dp4p | grep base-$pyver)" = "" ]
+  then
+    echo "Failed to build a dockerfile. ($pyver)"
+    exit 1
+  fi
 done
 
 for pyver in py27 py34 py35 pypy27; do
diff --git a/docker/dp/dist b/docker/dp/dist
--- a/docker/dp/dist
+++ b/docker/dp/dist
@@ -4,8 +4,18 @@ account="why2pac"
 dpver=$(./dpver)
 
 for pyver in py27 py34 py35 pypy27; do
+  sudo docker rmi $account/dp4p:$dpver-$pyver
+  sudo docker rmi $account/dp4p:latest-$pyver
+
+  sudo docker build --tag dp4p/$dpver-$pyver --build-arg dpver=$dpver ./$pyver
   sudo docker build --tag $account/dp4p:$dpver-$pyver --build-arg dpver=$dpver ./$pyver
   sudo docker build --tag $account/dp4p:latest-$pyver --build-arg dpver=$dpver ./$pyver
+
+  if [ "$(sudo docker images | grep $account/dp4p | grep $dpver-$pyver)" = "" ]
+  then
+    echo "Failed to build a dockerfile. ($pyver)"
+    exit 1
+  fi
 done
 
 for pyver in py27 py34 py35 pypy27; do
